- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: coreutils }
      - { name: git }
      - { name: zsh }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: lv }
      - { name: nkf }
      - { name: jq }
      - { name: go }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: rbenv }
      - { name: mysql }
      - { name: redis }
      - { name: w3m }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: cmake }
      - { name: ag }
      - { name: libtool }
      - { name: tig }
      - { name: vim }
      - { name: fzf }
      - { name: yarn, install_options: without-node}
#      - { name: ricty }
#      - { name: synx }
    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: google-chrome }
      - { name: skype }
      - { name: slack }
      - { name: skitch }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: alfred }
      - { name: hammerspoon }
      - { name: sip }
      - { name: boostnote }
      - { name: grammarly }

  tasks:
    - name: add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: '{{ homebrew_taps }}'

    - name: update homebrew
      homebrew: update_homebrew=yes

    # brew
    - name: install brew package
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: '{{ homebrew_packages }}'
      register: brew_result

    # cask
    - name: install cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: '{{ homebrew_cask_packages }}'
      register: cask_result

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
